'\" t
.\"     Title: virtualenv
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 12/02/2009
.\"    Manual:
.\"    Source:
.\"  Language: English
.\"
.TH "VIRTUALENV" "1" "12/02/2009" "" ""
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
virtualenv \- create virtual Python instances
.SH "SYNOPSIS"
.sp
\fBvirtualenv\fR [\fI\-\-version\fR] [\fI\-\-help\fR] [\fI\-\-verbose\fR] [\fI\-\-quiet\fR] [\fI\-\-clear\fR] [\fI\-\-no\-site\-packages\fR] [\fIdestination\-directory\fR]
.SH "DESCRIPTION"
.sp
virtualenv creates virtual Python executables, each of which can have its own set of installed modules\&. Programs that require different versions of modules or sets of modules that may be incompatible with others to be installed on the same system without conflicts\&.
.sp
The result is a directory containing its own Python executables (in DIR/bin/pythonVER and DIR/bin/python) and its own module directory containing the standard library as installed by the system\&. Additional modules may be installed via setuptools, as invoked from the binary directory (DIR/bin/easy_install)\&. The system\(aas site\-packages directories will be available, but can be overridden with locally\-installed modules\&.
.sp
In addition, a shell script called "activate" will be installed in the bin directory\&. If sourced, this will cause normal invokations of the Python executable to use the virtual environment\&.
.sp
By running the virtualenv command explicitly under the desired Python interpreter, the user can control which version of Python is created in the virtual environment\&.
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
Show summary of options\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Show the version of the program\&.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Be more verbose\&.
.RE
.PP
\fB\-q, \-\-quiet\fR
.RS 4
Be less verbose; suppress unimportant output\&.
.RE
.PP
\fB\-\-clear\fR
.RS 4
Clear out a previously\-created virtual Python instance in this location before creating a new one\&.
.RE
.PP
\fB\-p PYTHON_EXE,\-\-python=PYTHON_EXE\fR
.RS 4
The Python interpreter to use to create the new environment\&.
.RE
.PP
\fB\-\-no\-site\-packages\fR
.RS 4
Don\(aat give access to the global site\-packages modules to the virtual environment\&.
.RE
.PP
\fB\-\-unzip\-setuptools\fR
.RS 4
Unzip Setuptools or Distribute when installing it\&.
.RE
.PP
\fB\-\-relocatable\fR
.RS 4
Make an EXISTING virtualenv environment relocatable\&.
.RE
.PP
\fB\-\-distribute\fR
.RS 4
Ignored.  Distribute is used by default.  See \fB\-\-setuptools\fR to use Setuptools instead of Distribute\&.
.RE
.PP
\fB\-\-setuptools\fR
.RS 4
Use Setuptools instead of Distribute. Set environ variable VIRTUALENV_USE_SETUPTOOLS to make it the default\&.
.RE
.PP
\fB\-\-prompt==PROMPT\fR
.RS 4
Provides an alternative prompt prefix for this environment\&.
.SH "AUTHORS"
.sp
.if n \{\
.RS 4
.\}
.nf
This manual page was originally written by Jeff Licquia <licquia@debian\&.org>, later rewritten by Carl Chenet <chaica@ohmytux\&.com>\&.
.fi
.if n \{\
.RE
.\}
.SH "LICENSE"
.sp
.if n \{\
.RS 4
.\}
.nf
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, version 2 or any later version published by the Free Software Foundation\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.
.fi
.if n \{\
.RE
.\}
.SH "COPYRIGHT"
.sp
.if n \{\
.RS 4
.\}
.nf
Copyright \(co 2007 Jeff Licquia
.fi
.if n \{\
.RE
.\}
